---
title: "R Notebook"
output: html_notebook
---

# Heart Disease Prediction 
#### This project aim to detect or predict heart disease

```{r}
# Import libraries
library(tidyverse)
library(caret)
library(randomForest)
path <- 'F:/R programming/learning/ai_project/heart.csv'

df <- read.csv(path)


nrow(df)
summary(df)
head(df)
plot(df)



```
# Data PreProcessing & Visualization

```{r}
# convert target variable to factor ( 0 = No Disease , 1 = Disease)
df$target <- factor(df$target , levels = c(0,1))


#check missing values
sum(is.na(df)) ##no missing values 

# Visualize age distribution
ggplot(df,aes(x = age , fill = target)) + 
  geom_histogram(binwidth = 5 , alpha = 0.7) + 
  scale_fill_manual(values = c("green","orange"), labels = c("No Disease" , "Heart Disaease") )

```
# Step 4 : Split data into train & Test sets 

```{r}
library(caTools)
set.seed(123)
trainIndex <- sample.split(df$target , SplitRatio = 0.80)

# split data 
train <- subset(df , trainIndex)
test <- subset(df,!trainIndex)



```

# step 5 : Train a Random Forest Model 

```{r}
model <- randomForest(target ~ ., data = train , ntree = 100 )
predictions <- predict(model , test) 

# confusion matrix creation
confusionMatrix(predictions,test$target)

```

# Step 6: Save the Model & R Markdown File 

```{r}
saveRDS(model,"heart_disease_model.rds")
```



